EmprestimoApp/Models/Cliente.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace EmprestimoApp.Models
{
    public class Cliente
    {
        [Key]
        public int Id { get; set; }
        public string Nome { get; set; }
        public int Idade { get; set; }
        public double Score { get; set; }
        [DisplayName("Saldo Total")]
        public double SaldoAtual { get; set; }
        public Emprestimo Emprestimo { get; set; }
    }
}

EmprestimoApp/Models/Emprestimo.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace EmprestimoApp.Models
{
    public class Emprestimo
    {
        [Key]
        public int Id { get; set; }
        public int ClienteId { get; set; }
        [DisplayName("Valor do Emprestimo")]
        public double ValorEmprestimo { get; set; }
        [DisplayName("Quantidade Parcelas")]
        public int QuantidadeParcelas { get; set; }
        [DisplayName("Valor da Parcela")]
        public double ValorDaParcela { get; set; }
        [DisplayName("Valor Total")]
        public double valorTotal { get; set; }
        [DisplayName("Id")]
        public Cliente Cliente { get; set; }

        public double ValorTotal(double valorEmprestimo)
        {
            return valorEmprestimo += valorEmprestimo * 0.39;
        }

        public double ValorParcela(double valorTotal, double qtdParcelas)
        {
            return valorTotal / qtdParcelas;
        }
    }
}

EmprestimoApp/Models/ErrorViewModel.cs
namespace EmprestimoApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EmprestimoApp/Controllers/ClienteController.cs
using EmprestimoApp.DataContext;
using EmprestimoApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmprestimoApp.Controllers
{
    public class ClienteController : Controller
    {
        private readonly Context _context;

        public ClienteController(Context context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var result = _context.Clientes.ToList();
            return View(result);
        }

        
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Cliente cliente)
        {
            if (!ModelState.IsValid) return View(cliente);
                       
            _context.Clientes.Add(cliente);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

EmprestimoApp/Controllers/EmprestimoController.cs
using EmprestimoApp.DataContext;
using EmprestimoApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmprestimoApp.Controllers
{
    public class EmprestimoController : Controller
    {
        private readonly Context _context;

        public EmprestimoController(Context context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var result = _context.Emprestimos.ToList();
            return View(result);
        }

        public IActionResult Create(int id)
        {
            var emprestimo = new Emprestimo();
            emprestimo.ClienteId = id;

            return View(emprestimo);
        }

        [HttpPost]
        public IActionResult Create(Emprestimo emprestimo)
        {

            if (!ModelState.IsValid) return View(emprestimo);
            emprestimo.Id = 0;

            var calc = emprestimo.ValorTotal(emprestimo.ValorEmprestimo);
            emprestimo.valorTotal = calc;

            var parcelas = emprestimo.ValorParcela(calc, emprestimo.QuantidadeParcelas);
            emprestimo.ValorDaParcela = parcelas;

            var cliente = _context.Clientes.FirstOrDefault(x => x.Id == emprestimo.ClienteId);

            emprestimo.Cliente = cliente;

            emprestimo.Cliente.SaldoAtual += emprestimo.ValorEmprestimo;
            
            _context.Emprestimos.Add(emprestimo);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }


    }
}

EmprestimoApp/Controllers/HomeController.cs
using EmprestimoApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EmprestimoApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EmprestimoApp/Views/Cliente/Create.cshtml
@model EmprestimoApp.Models.Cliente

@{
    ViewData["Title"] = "Novo Cliente";
}

<h4>@ViewData["Title"]</h4>
<h3>
    @ViewData["Teste"]
</h3>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idade" class="control-label"></label>
                <input asp-for="Idade" class="form-control" />
                <span asp-validation-for="Idade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Score" class="control-label"></label>
                <input asp-for="Score" class="form-control" />
                <span asp-validation-for="Score" class="text-danger"></span>
            </div>
               <div class="form-group">
                <label asp-for="SaldoAtual" class="control-label"></label>
                <input asp-for="SaldoAtual" class="form-control" />
                <span asp-validation-for="SaldoAtual" class="text-danger"></span>
            </div>
            <div class="form-group" style="margin-top:10px">
                <input type="submit" value="Adicionar" class="btn btn-primary" />
                <a class="btn btn-outline-info" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");


    }
}

EmprestimoApp/Views/Cliente/Index.cshtml
@model IEnumerable<EmprestimoApp.Models.Cliente>

@{
    ViewData["Title"] = "Clientes";
}

<h4>@ViewData["Title"]</h4>
<p>
    <a class="btn btn-outline-primary" asp-action="Create">Novo Cliente</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Score)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SaldoAtual)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Idade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Score)
            </td>
             <td>
                @Html.DisplayFor(modelItem => item.SaldoAtual)
            </td>
            <td>
              <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id">Detalhes</a>
              <a class="btn btn-outline-primary" asp-controller="Emprestimo" asp-route-id="@item.Id" asp-action="Create">Pedir Empréstimo</a>
            </td>
        </tr>
}
    </tbody>
</table>

EmprestimoApp/Views/Emprestimo/Create.cshtml
@model EmprestimoApp.Models.Emprestimo

@{
    ViewData["Title"] = "Novo Empréstimo";
}

<h4>@ViewData["Title"]</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <input type="hidden" asp-for="ClienteId" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ValorEmprestimo" class="control-label"></label>
                <input asp-for="ValorEmprestimo" class="form-control" />
                <span asp-validation-for="ValorEmprestimo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuantidadeParcelas" class="control-label"></label>
                <input asp-for="QuantidadeParcelas" class="form-control" />
                <span asp-validation-for="QuantidadeParcelas" class="text-danger"></span>
            </div>
            @*<div class="form-group">
            <label asp-for="ClienteId" class="control-label"></label>
            <select asp-for="ClienteId" class ="form-control" asp-items="ViewBag.ClienteId"></select>
            </div>*@
            <div class="form-group" style="margin-top:10px">
                <input type="submit" value="Criar" class="btn btn-info" />
                <a class="btn btn-primary" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

EmprestimoApp/Views/Emprestimo/Index.cshtml
@model IEnumerable<EmprestimoApp.Models.Emprestimo>

@{
    ViewData["Title"] = "Index";
}

<h4>Index</h4>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ValorEmprestimo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.QuantidadeParcelas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.valorTotal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorDaParcela)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ValorEmprestimo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuantidadeParcelas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.valorTotal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cliente.Id)
            </td>
             <td>
                @Html.DisplayFor(modelItem => item.ValorDaParcela)
            </td>
@*            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>*@
        </tr>
}
    </tbody>
</table>

EmprestimoApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EmprestimoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmprestimoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmprestimoApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EmprestimoApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Emprestimo" asp-action="Index">Emprestimos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EmprestimoApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>